version: "3.9"
services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    # depends_on:
    #   - backend
    volumes: # ローカルとコンテナのパスをマウント
      # - ./frontend:/frontend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    # working_dir: /frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}
    security_opt:
      - seccomp:unconfined
